- name: Install Cockpit
  community.general.pacman:
    name:
      - cockpit
      - cockpit-packagekit
      - cockpit-pcp
      - cockpit-storaged
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: (system.cockpit == true )
