---

- ansible.builtin.import_tasks: userconfig.yml
  name: userconfig
- ansible.builtin.import_tasks: base.yml
  name: base
- ansible.builtin.import_tasks: ntp.yml
  name: ntp
- ansible.builtin.import_tasks: locale.yml
  name: locale
- ansible.builtin.import_tasks: userconf-dropin.yml
  name: Local system customizations -- systemd/user.conf dropin
- ansible.builtin.import_tasks: makepkg.yml
  name: Local system customizations -- /etc/makepkg.conf