---

- name: Install rEFInd bootloader and tools
  pacman: name=refind state=present
  when: bootloader == "refind"

- name: Get boot device UUID
  shell: "blkid -s UUID -o value {{ root_device }}"
  register: refind_root_uuid

- name: Get swap device UUID
  shell: "cat /etc/fstab | grep swap | cut -f 1 -d \" \""
  register: refind_swap_uuid

- name: Populate kernel command line root file
  ansible.builtin.template:
    src: refind_linux.conf.j2
    dest: /boot/refind_linux.conf
  become: yes
  when:
    - refind_root_uuid
    - refind_swap_uuid
