- name: Install rEFInd bootloader and tools
  community.general.pacman:
    name: refind
    state: present
  when: bootloader == "refind"
  register: refind_pkg_installed

- name: Install refind to EFI
  ansible.builtin.command: refind-install --yes
  when: refind_pkg_installed

- name: Get boot device UUID
  ansible.builtin.shell: "blkid -s UUID -o value {{ root_device }}"
  register: refind_root_uuid

- name: Get swap device UUID
  ansible.builtin.shell: 'cat /etc/fstab | grep swap | grep UUID | cut -f 1'
  register: refind_swap_uuid
- name: Populate kernel command line root file
  ansible.builtin.template:
    src: refind_linux.conf.j2
    dest: /boot/refind_linux.conf
    perms: 0644
  become: true
  when:
    - refind_root_uuid
    - refind_swap_uuid

- name: Create /etc/pacman.d/hooks/ directory
  ansible.builtin.file:
    path: /etc/pacman.d/hooks/
    state: directory
    mode: "0755"
  register: created_pacmand_hooks_dir

- name: Deploy refind hook
  ansible.builtin.copy:
    src: refind.hook
    dest: /etc/pacman.d/hooks/
    perms: 0644
  when: created_pacmand_hooks_dir
