- name: Install printing tools
  ansible.builtin.package:
    name:
      - cups
      - cups-pk-helper
    state: present
  register: cups_installed
- name: Enable cups service
  ansible.builtin.service:
    name: cups
    state: started
    enabled: true
  when: cups_installed
