- name: Install printing tools
  community.general.pacman:
    name: "{{ item }}"
    with_items:
      - cups
      - cups-pk-helper
    state: present
  until: cups_installed is success
  retries: 2
  delay: 2
  register: cups_installed
- name: Enable cups service
  ansible.builtin.service:
    name: cups
    state: started
    enabled: true
  when: cups_installed
