---

- name: Install printing tools
  ansible.builtin.package:
    name:
      - cups
      - cups-pk-helper
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Enable cups service
  ansible.builtin.service:
    name: cups
    state: started
    enabled: true
