---

- name: Install Syncthing
  pacman:
    name: "{{ item }}"
  with_items:
    - syncthing

- name: Install Syncthingtray
  kewlfft.aur.aur:
    name:
      - syncthingtray-qt6
    use: yay
  become: yes
  become_user: "{{ user.name }}"

- name: Enable Syncthing@user service
  ansible.builtin.service:
    name: "syncthing@{{ user.name }}"
    state: started
    enabled: true
