- name: install additional GUI packages common to all environments
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - btrfs-assistant
    - darkman
    - gst-plugins-bad
    - gst-plugins-good
    - gst-plugins-ugly
    - gtk4
    - mupdf
    - mupdf-tools
    - openrgb
    - prison5
    - trash-cli
    - variety
    - zathura-cb
    - zathura-pdf-mupdf
    - zathura-ps
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
- name: install additional GUI packages common to all environments from aur
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
  become: true
  become_user: "{{ user.name }}"
  with_items:
    - btrfsmaintenance
    - easyeffects
    - raw-thumbnailer
    - visual-studio-code-bin
    - winbox
