- name: install dunst notification server
  community.general.pacman:
    executable: powerpill
    name: dunst
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
