- name: install fonts
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  with_items:
    - fontconfig
    - noto-fonts-emoji
    - ttf-dejavu
    - ttf-droid
    - ttf-font-awesome
    - ttf-liberation
    - xorg-font-util
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
- name: install aur fonts
  kewlfft.aur.aur:
    name:
      - apple-fonts
      - nerd-fonts-sf-mono
      - ttf-mac-fonts
      - ttf-meslo-nerd-font-powerlevel10k
    use: yay
  become: true
  become_user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
