---

- name: install fonts
  pacman:
    name:
      - ttf-dejavu
      - ttf-liberation
      - ttf-droid
      - noto-fonts-emoji
      - fontconfig
      - xorg-font-util
      - ttf-font-awesome
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install aur fonts
  kewlfft.aur.aur:
    name:
      - powerline-fonts-git
      - ttf-meslo-nerd-font-powerlevel10k
      - apple-fonts
      - nerd-fonts-sf-mono
      - ttf-mac-fonts
    use: yay
  become: yes
  become_user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
