---

- name: install fonts
  pacman:
    name:
      - ttf-dejavu
      - ttf-liberation
      - ttf-droid
      - noto-fonts-emoji
      - fontconfig
      - xorg-font-util
      - ttf-font-awesome
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install aur fonts
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - powerline-fonts-git
    - oh-my-zsh-git
    - ttf-meslo-nerd-font-powerlevel10k
    - apple-fonts
    - nerd-fonts-sf-mono
    - ttf-mac-fonts
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
