---
- name: install KDE Plasma meta package
  pacman:
      name: "{{ item }}"
      state: present
  with_items:
      - plasma-meta
      - sddm
  when: kde == true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install KDE PIM
  pacman:
      name: "{{ item }}"
      state: present
  with_items:
      - akonadi-calendar-tools
      - akonadiconsole
      - akregator
      - grantlee-editor
      - itinerary
      - kaddressbook
      - kalarm
      - kdepim-addons
      - kleopatra
      - kmail
      - knotes
      - kontact
      - korganizer
      - merkuro
      - zanshin
  when: kdepim == true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install KDE additions
  pacman:
      name: "{{ item }}"
      state: present
  with_items:
      - alligator
      - appmenu-gtk-module
      - ark
      - audiocd-kio
      - breeze-plymouth
      - colord-kde
      - dolphin
      - dolphin-plugins
      - dragon
      - elisa
      - ffmpegthumbs
      - filelight
      - flatpak-kcm
      - ghostwriter
      - gnuchess
      - gwenview
      - isoimagewriter
      - juk
      - k3b
      - kalk
      - kamera
      - kamoso
      - kapptemplate
      - kasts
      - kate
      - kbackup
      - kcachegrind
      - kcalc
      - kcharselect
      - kclock
      - kcolorchooser
      - kcron
      - kde-dev-scripts
      - kde-dev-utils
      - kde-inotify-survey
      - kdebugsettings
      - qt6-connectivity
      - kpeople
      - libfakekey
      - kdegraphics-thumbnailers
      - kdenetwork-filesharing
      - kdenlive
      - kdesdk-kio
      - kdesdk-thumbnailers
      - kdf
      - kdialog
      - kdiff3
      - keditbookmarks
      - kfind
      - kgpg
      - khelpcenter
      - kimagemapeditor
      - kimageformats
      - kio-admin
      - kio-extras
      - kio-gdrive
      - kio-zeroconf
      - kirigami-gallery
      - kjournald
      - kmag
      - kmahjongg
      - kmines
      - kmousetool
      - kmouth
      - knights
      - koko
      - kolf
      - kolourpaint
      - kompare
      - kongress
      - konsole
      - kontrast
      - konversation
      - krdc
      - krecorder
      - krfb
      - kruler
      - ksystemlog
      - kteatime
      - ktimer
      - ktorrent
      - ktrip
      - kwalletmanager
      - kwave
      - kweather
      - lokalize
      - markdownpart
      - neochat
      - okteta
      - okular
      - partitionmanager
      - plasma-sdk
      - plymouth-kcm
      - poxml
      - qt6-tools
      - skanlite
      - skanpage
      - spectacle
      - svgpart
      - sweeper
      - system-config-printer
      - tesseract-data-eng
      - tokodon
      - xwaylandvideobridge
      - yakuake
      - meld
  when: kde == true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: deploy sddm wayland configuration file
  ansible.builtin.copy:
      src: 10-wayland.conf
      dest: /etc/sddm.conf.d/

- name: Enable sddm service
  ansible.builtin.service:
      name: sddm
      state: started
      enabled: true

- name: amd-specific gaming items
  kewlfft.aur.aur:
      name:
          - plasma-gamemode-git
          - kdeconnect-no-mdns
      use: yay
  when: system.games == true
  become: true
  become_user: "{{ user.name }}"
