---

- name: install KDE Plasma meta package
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
      - plasma-meta
      - sddm
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install KDE additions
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
      - alligator
      - trash-cli
      - appmenu-gtk-module
      - ark
      - audiocd-kio
      - breeze-plymouth
      - colord-kde
      - dolphin
      - dolphin-plugins
      - dragon
      - elisa
      - ffmpegthumbs
      - filelight
      - flatpak-kcm
      - ghostwriter
      - gnuchess
      - gwenview
      - isoimagewriter
      - juk
      - k3b
      - kalk
      - kamera
      - kamoso
      - kapptemplate
      - kasts
      - kate
      - kbackup
      - kcachegrind
      - kcalc
      - kcharselect
      - kclock
      - kcolorchooser
      - kcron
      - kde-dev-scripts
      - kde-dev-utils
      - kde-inotify-survey
      - kdebugsettings
      - kdeconnect
      - kdegraphics-thumbnailers
      - kdenetwork-filesharing
      - kdenlive
      - kdesdk-kio
      - kdesdk-thumbnailers
      - kdf
      - kdialog
      - kdiff3
      - keditbookmarks
      - kfind
      - kgpg
      - khelpcenter
      - kimagemapeditor
      - kimageformats
      - kio-admin
      - kio-extras
      - kio-gdrive
      - kio-zeroconf
      - kirigami-gallery
      - kjournald
      - kmag
      - kmahjongg
      - kmines
      - kmousetool
      - kmouth
      - knights
      - koko
      - kolf
      - kolourpaint
      - kompare
      - kongress
      - konsole
      - kontrast
      - konversation
      - krdc
      - krecorder
      - krfb
      - kruler
      - ksystemlog
      - kteatime
      - ktimer
      - ktorrent
      - ktrip
      - kwalletmanager
      - kwave
      - kweather
      - lokalize
      - markdownpart
      - neochat
      - okteta
      - okular
      - partitionmanager
      - plasma-sdk
      - plymouth-kcm
      - poxml
      - skanlite
      - skanpage
      - spectacle
      - svgpart
      - sweeper
      - system-config-printer
      - tesseract-data-eng
      - tokodon
      - tuned-ppd
      - xwaylandvideobridge
      - yakuake
  when: kde == 'yes'
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: deploy sddm wayland configuration file
  ansible.builtin.copy:
    src: 10-wayland.conf
    dest: /etc/sddm.conf.d/


- name: Enable sddm service
  ansible.builtin.service:
    name: sddm
    state: started
    enabled: true
