- name: install additional GUI packages common to all environments
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - kvantum
    - kvantum-theme-materia
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
- name: Install Kvantum QT6 theme engine items from aur
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
  become: true
  become_user: "{{ user.name }}"
  with_items:
    - kvkonqi
