---
- name: Install ZSH with completion and syntax
  pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present
  register: zshinstall
  until: zshinstall is success
  retries: 10
  delay: 2
  notify: change shell
