---

- name: install neovim
  pacman:
    name: neovim
    state: present

- name: install Sublime Text
  kewlfft.aur.aur:
    name:
      - sublime-text-4
    use: yay
  become: true
  become_user: "{{ user.name }}"
  when: system_type == "desktop"
  
- name: install obsidian
  pacman:
    name: obsidian
    state: present
  when: system_type == "desktop"
  
- name: install Libre Office (fresh)
  pacman:
    name: libreoffice-fresh
    state: present
  when: system_type == "desktop"
  
- name: install VSCode
  kewlfft.aur.aur:
    name:
      - visual-studio-code-bin
    use: yay
  when: system_type == "desktop"
  become: true
  become_user: "{{ user.name }}"
