---

- name: install neovim
  pacman:
    name: neovim
    state: present

- name: install Sublime Text
  kewlfft.aur.aur:
    name:
      - sublime-text-4
    use: yay
  become: yes
  become_user: "{{ user.name }}"