---

- name: install key from default keyserver on target machine
  gpg_key:
    fpr: 5fc8fe1141fa769594e91e48f41bdbf6171a3bb4
    homedir: "~{{ user.name }}/.gnupg"
  become: yes
  become_user: "{{ user.name }}"

- name: deploy gpg preexec file with corrected pinentry
  ansible.builtin.copy: src=preexec dest=/etc/pinentry/