---

- name: Copy my public key to temporary file
  ansible.builtin.copy: src=mykey.asc dest=/tmp/
  register: staged_my_key

- name: Add my public key to my gpg keyring
  gpg_key:
    file: /tmp/mykey.asc
    trust: 5
  become: yes
  become_user: "{{ user.name }}"
  when: staged_my_key
  register: imported_my_key

- name: Remove my public key temp file
  ansible.builtin.file:
    src: /tmp/mykey.asc
    state: absent
  when: imported_my_key

- name: deploy gpg preexec file with corrected pinentry
  ansible.builtin.copy: src=preexec dest=/etc/pinentry/
