- name: Install kernel
  ansible.builtin.import_tasks: kernels.yaml

- name: Configure Unified Kernel Image (uki)
  ansible.builtin.import_tasks: uki.yaml
  when: uki

- name: Push mkinitcpio configuration
  ansible.builtin.template:
    src: mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf.d/mkinitcpio-override.conf
    mode: '0644'
  notify:
    - Regenerate initramfs

- name: Firmware
  community.general.pacman:
    name:
      - linux-firmware
      - sof-firmware
    state: present
  notify:
    - Regenerate initramfs

- name: Run mkinitcpio
  ansible.builtin.command: "mkinitcpio -P"
  become: true
  register: output
