---

- name: Install firefox
  pacman: name=firefox state=present
  tags:
    - firefox


- name: install Brave from AUR
  kewlfft.aur.aur:
    name:
      - brave-bin
    use: yay
  become: yes
  become_user: "{{ user.name }}"
