---

- name: Install firefox
  pacman: name=firefox state=present
  tags:
    - firefox

- name: install Brave from AUR
  aur:
    name: brave-bin
    user: "{{ user.name }}"
  with_items:
    - brave-bin
