- name: Install photography tools
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  with_items:
    - gimp
    - darktable
    - rawtherapee
    - shotwell
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
