---

- name: Install photography tools
  pacman:
    name:
      - gimp
      - darktable
      - rawtherapee
      - shotwell
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
