# Arch de minimis distribution
# ====================
# IMPORTANT:  Changing this from "arch" will override some settings below.
# options:
#   "arch", vanilla arch linux
#   "cachyos", CachyOS
###
system_distribution: "arch"

##
# Inside a chroot environment?
# ============================
##
chrooted: true

##
# Linux Kernel
# ============
# For details, see https://wiki.archlinux.org/title/Kernel
# Kernels:
#   Option: "linux" Vanilla Linux kernel and modules, with a few patches applied.
#   Option: "linux-hardened" A security-focused Linux kernel
#   Option: "linux-zen" The result of a collaborative effort of kernel hackers to provide the best Linux kernel possible for everyday systems.
#
# Leave this blank for CachyOS or other systems where you don't want to specify a kernel.
##
kernel: "linux-zen"

##
# UKI: Unified Kernel Image
# =========================
# Generate a UKI image instead of a classic image?
# true/false
##
uki: false

##
# User configuration
# ==================
# Pretty self-explanatory.
# name: The user id
# shell: Name of the desired shell (bash/zsh/fish)
#
##
user:
  name: alberth
  shell: fish

##
# System configuration
# ====================
# type:  ***IMPORTANT:  Setting this to server will override any desktop settings below***
#   "desktop", install additional items associated with a desktop environment
#   "minimal", or "", The minimal required options
#     - kernel
#     - base OS
#     - My preferred minimal toolkit
#     - firewall
#     - networking
# processor:
#   Option: "intel" will install microcode updates and configure the bootloader accordingly
#   Option: "amd" will do the same for amd
# graphics_card:
#   Option: "intel" will install intel graphics drivers
#   Option: "amd" will install amd drivers
#   Option: "nvidia" will install nouveau because i will NEVER EVER touch those filthy nvidia drivers
#                    if you wan't proprietary drivers follow the steps documented in the arch wiki.
# pacoloco: Install custom pacoloco mirror
# cockpit:  Install web management UI
##
system:
  hostname: ""
  pacman: true
  makepkg: true
  cockpit: true
  locale: "en_US.UTF-8"
  timezone: "America/New_York"
  processor: "amd"
  graphics_card: "amd"
  macspoof: false
  type: ""

############# Desktop Envionment Settings ####################
####                                                      ####
####                                                      ####
##
# Install KDE
# ===========
# true/false to installing KDE Plasma and/or kde-pim.  kde-pim alone will install
# some parts of kde, but not all of plasma
##
kde: false
kdepim: false

##
# Install Hyprland
# ================
# true/false to install Hyprland
##
hyprland: false
hyprland_settings:
  gdm: false
  gnome: false
  greetd: false
  kde: false
  mako: false
  sddm: false
  sddm_wayland: false
  thunar: false
  hyprland_git: true

##
# Install Gnome
# =============
# true/false to install Hyprland
##
gnome: false

##
# Install Cosmic
# ==============
# true/false to install Hyprland
##
cosmic: false
####                                                      ####
####                                                      ####
##############################################################

##
# Enable chaotic-aur
# ==================
# true/false
##
enable_chaotic: false

##
# Firewall configuration
# ========================
# ufw and firewalld are supported
##
firewall: "firewalld"

##
# Bootloader configuration
# ========================
# refind and grub are supported
##
bootloader: "refind"

##
# Cryptdevice config
# ========================
# The device name of your luks device
##
#cryptdevice: /dev/nvmen1p2
cryptdevice: false

##
# Connectivity configuration
# ==========================
##
ssh:
  port: 22
  enable_sshd: true

##
# Use systemd-resolved stub DNS resolver (and cache)
# =================
##
resolved_stub: false

##
# Install TeX live
# =================
##
TeXlive: false

##
# Install QEMU Virtualization
# =================
##
qemu: false
