# Arch distribution
# ====================
# IMPORTANT:  Changing this from "arch" will override some settings below.
# options:
#   "arch", vanilla arch linux
#   "cachyos", CachyOS
###
system_distribution: "arch"
##
# Linux Kernel
# ============
# For details, see https://wiki.archlinux.org/title/Kernel
# Kernels:
#   Option: "linux" Vanilla Linux kernel and modules, with a few patches applied.
#   Option: "linux-hardened" A security-focused Linux kernel
#   Option: "linux-zen" The result of a collaborative effort of kernel hackers to provide the best Linux kernel possible for everyday systems.
#
# Leave this blank for CachyOS or other systems where you don't want to specify a kernel.
##
kernel: "linux-zen"
##
# User configuration
# ==================
##
user:
  name: alberth
  group: users
  shell: /bin/fish
##
# System configuration
# ====================
# processor type:
# type:  ***IMPORTANT:  Setting this to server will override any desktop settings below***
#   "desktop", install additional items associated with a desktop environment
#   "server", secure and simple install.
# processor:
#   Option: "intel" will install microcode updates and configure the bootloader accordingly
#   Option: "amd" will do the same for amd
# graphics_card type:
#   Option: "intel" will install intel graphics drivers
#   Option: "amd" will install amd drivers
#   Option: "nvidia" will install nouveau because i will NEVER EVER touch those filthy nvidia drivers
#                    if you wan't proprietary drivers follow the steps documented in the arch wiki.
# pacoloco: Install custom pacoloco mirror
# cockpit:  Install web management UI
##
system:
  pacman: true
  pacoloco: false
  makepkg: true
  cockpit: true
  games: true
  bluetooth: true
  locale: "en_US.UTF-8"
  timezone: "America/New_York"
  processor: "amd"
  graphics_card: "amd"
  macspoof: false
  type: "desktop"
##
# Firewall configuration
# ========================
# ufw and firewalld are supported
##
firewall: "firewalld"
##
# Use Oracle BPFTune
# ==================
# Oracle's auto-tuning daemon reacts to system needs and adjusts sysctl tunings automatically.
# BUT, any user-set sysctl will make bpftune ignore recommendations for that parameter,
# So, if this is enabled, we DO NOT apply custom sysctl parameters.
##
use_bpftune: true
##
# Bootloader configuration
# ========================
# refind and grub are supported
##
bootloader: "refind"
##
# Cryptdevice config
# ========================
# The device name of your luks device
##
#cryptdevice: /dev/nvmen1p2
cryptdevice: false
##
# Connectivity configuration
# ==========================
##
ssh:
  port: 22
  enable_sshd: true
##
# Use systemd-resolved stub DNS resolver (and cache)
# =================
##
resolved_stub: true
##
# Dotfile configuration
# =====================
# Choose whether custom dotfiles should be installed or not
# Just set the installation flag to false to avoid an installation
##
dotfiles:
  installation: false
  url: https://github.com/amatos/dotfiles.git
  destination: .dotfiles
  rcup_flags: -fx README.md
##
# Install Keypassxc
# =================
# true/false to installing keypassxc
##
keepass: false
##
# Install KDE
# =================
# true/false to installing KDE Plasma and/or kde-pim.  kde-pim alone will install
# some parts of kde, but not all of plasma
##
kde: true
kdepim: true
##
# Install thunderbird
# ===================
# true/false to install thunderbird
##
thunderbird: false
##
# Install gitkraken
# =================
# true/false to installing GitKraken
##
gitkraken: true
##
# Install JetBrains IDEs?
# =================
# true/false to installing CLion and IntelliJ
##
install_jetbrains: false
##
# Install QEMU
# =================
# true/false to installing QEMU, virt-manager, and samba
##
install_qemu: true
##
# Base package configuration
# ==========================
##
base_packages:
  - avahi
  - base-devel
  - bind
  - btop
  - chrony
  - cmake
  - coreutils
  - cronie
  - curl
  - dateutils
  - fish
  - fwupd
  - geoclue
  - git
  - go
  - jdk-openjdk
  - links
  - lsof
  - man-db
  - man-pages
  - ninja
  - nmap
  - nodejs
  - npm
  - nss-mdns
  - openssh
  - pacman-contrib
  - perl
  - pkgstats
  - python
  - python-jmespath
  - python-pipx
  - reflector
  - rkhunter
  - rsync
  - ruby
  - rust
  - strace
  - sysstat
  - texinfo
  - tmux
  - zsh
##
# Misc. packages
# ==============
##
misc_packages:
  - ansible-language-server
  - ansible-lint
  - argyllcms
  - aria2
  - arj
  - atomicparsley
  - bash-completion
  - bash-language-server
  - bat
  - bc
  - catdoc
  - ccache
  - cdrdao
  - cdrtools
  - colord-sane
  - cowsay
  - ctags
  - diff-so-fancy
  - dosfstools
  - dvd+rw-tools
  - emovix
  - exfatprogs
  - eza
  - f2fs-tools
  - fatresize
  - festival
  - fortune-mod
  - fzf
  - gavl
  - geoipupdate
  - git-delta
  - graphviz
  - gum
  - hunspell-en_us
  - inotify-tools
  - jfsutils
  - ladspa
  - languagetool
  - libappimage
  - libdvdcss
  - libgtop
  - libid3tag
  - libsynctex
  - libwmf
  - lolcat
  - lrzip
  - lua-language-server
  - lzop
  - mediainfo
  - mlocate
  - movit
  - nss-mdns
  - ntfs-3g
  - opencv
  - openmp
  - opentimelineio
  - p7zip
  - pacman-contrib
  - pacutils
  - pbzip2
  - pigz
  - pkgfile
  - power-profiles-daemon
  - pstoedit
  - python-lsp-server
  - python-setuptools
  - ruby-docs
  - sane-airscan
  - shellcheck
  - snap-pac
  - snapper
  - speech-dispatcher
  - sshfs
  - starship
  - strace
  - subversion
  - tesseract
  - tesseract-data-eng
  - tesseract-data-por
  - udftools
  - unarchiver
  - unzip
  - vcdimager
  - wget
  - xfsprogs
  - yaml-language-server
  - yamlfmt
  - yamllint
##
# Misc. AUR packages
# ==============
##
aur_packages:
  - ansible-gpg-key-git
  - find-the-command
  - hunspell-pt-br
  - perl-bundle-camelcade
  - perl-devel-camelcadedb
##
# Gaming packages
# ===============
##
gaming_packages:
  - heroic-games-launcher-bin
  - protonup-qt
  - reshade-shaders-git
  - steamtinkerlaunch
  - vkbasalt
  - vkbasalt-cli
  - lib32-vkbasalt
  - gamemode
  - gamescope
  - goverlay
  - lib32-dbus
  - lib32-glu
  - lib32-libcurl-compat
  - lib32-mesa
  - lib32-nss
  - lib32-systemd
  - libva-mesa-driver
  - lutris
  - mangohud
  - mesa
  - sndio
  - steam
  - v4l2loopback-dkms
  - wf-recorder
