# Arch de minimis distribution
# ====================
# IMPORTANT:  Changing this from "arch" will override some settings below.
# options:
#   "arch", vanilla arch linux
#   "cachyos", CachyOS
###
system_distribution: "arch"

##
# Linux Kernel
# ============
# For details, see https://wiki.archlinux.org/title/Kernel
# Kernels:
#   Option: "linux" Vanilla Linux kernel and modules, with a few patches applied.
#   Option: "linux-hardened" A security-focused Linux kernel
#   Option: "linux-zen" The result of a collaborative effort of kernel hackers to provide the best Linux kernel possible for everyday systems.
#
# Leave this blank for CachyOS or other systems where you don't want to specify a kernel.
##
kernel: "linux-zen"

##
# UKI: Unified Kernel Image
# =========================
# Generate a UKI image instead of a classic image?
# true/false
##
uki: false

##
# User configuration
# ==================
# Pretty self-explanatory.
# name: The user id
# shell: Name of the desired shell (bash/zsh/fish)
#
##
user:
  name: alberth
  shell: fish

##
# System configuration
# ====================
# type:  ***IMPORTANT:  Setting this to server will override any desktop settings below***
#   "desktop", install additional items associated with a desktop environment
#   "minimal", or "", The minimal required options
#     - kernel
#     - base OS
#     - My preferred minimal toolkit
#     - firewall
#     - networking
# processor:
#   Option: "intel" will install microcode updates and configure the bootloader accordingly
#   Option: "amd" will do the same for amd
# graphics_card:
#   Option: "intel" will install intel graphics drivers
#   Option: "amd" will install amd drivers
#   Option: "nvidia" will install nouveau because i will NEVER EVER touch those filthy nvidia drivers
#                    if you wan't proprietary drivers follow the steps documented in the arch wiki.
# pacoloco: Install custom pacoloco mirror
# cockpit:  Install web management UI
##
system:
  hostname: ""
  pacman: true
  makepkg: true
  cockpit: true
  locale: "en_US.UTF-8"
  timezone: "America/New_York"
  processor: "amd"
  graphics_card: "amd"
  macspoof: false
  type: "desktop"

############# Desktop Envionment Settings ####################
####                                                      ####
####                                                      ####
##
# Install KDE
# ===========
# true/false to installing KDE Plasma and/or kde-pim.  kde-pim alone will install
# some parts of kde, but not all of plasma
##
kde: false
kdepim: false

##
# Install Hyprland
# ================
# true/false to install Hyprland
##
hyprland: true

##
# Install Gnome
# =============
# true/false to install Hyprland
##
gnome: false

##
# Install Cosmic
# ==============
# true/false to install Hyprland
##
cosmic: false
####                                                      ####
####                                                      ####
##############################################################

##
# Enable chaotic-aur
# ==================
# true/false
##
enable_chaotic: false

##
# Firewall configuration
# ========================
# ufw and firewalld are supported
##
firewall: "firewalld"

##
# Bootloader configuration
# ========================
# refind and grub are supported
##
bootloader: "refind"

##
# Cryptdevice config
# ========================
# The device name of your luks device
##
#cryptdevice: /dev/nvmen1p2
cryptdevice: false

##
# Connectivity configuration
# ==========================
##
ssh:
  port: 22
  enable_sshd: true

##
# Use systemd-resolved stub DNS resolver (and cache)
# =================
##
resolved_stub: false

##
# Base package configuration
# ==========================
##
minimal_packages:
  - avahi
  - base-devel
  - bash
  - bind
  - ccache
  - chrony
  - coreutils
  - cronie
  - curl
  - dateutils
  - fish
  - fwupd
  - git
  - links
  - lsof
  - man-db
  - man-pages
  - neovim
  - nss-mdns
  - openssh
  - pacman-contrib
  - pacutils
  - pbzip2
  - pigz
  - pkgfile
  - pkgstats
  - python
  - python-jmespath
  - python-pipx
  - reflector
  - rsync
  - sbctl
  - strace
  - sysstat
  - texinfo
  - udisks2
  - udisks2-btrfs
  - zsh
  - btop

##
# "Desktop" cli and gui packages
# ==============
##
desktop_cli:
  - ansible-gpg-key-git
  - ansible-language-server
  - ansible-lint
  - argyllcms
  - arj
  - atomicparsley
  - atuin
  - bash-completion
  - bash-language-server
  - bat
  - bc
  - catdoc
  - cdrdao
  - cdrtools
  - chezmoi
  - chezmoi_modify_manager
  - cmake
  - colord-sane
  - cowsay
  - ctags
  - diff-so-fancy
  - dosfstools
  - dvd+rw-tools
  - emovix
  - espanso-wayland-git
  - exfatprogs
  - eza
  - f2fs-tools
  - fatresize
  - festival
  - find-the-command
  - fortune-mod
  - fzf
  - gavl
  - geoclue
  - geoipupdate
  - git-delta
  - github-cli
  - gnuplot
  - go
  - graphviz
  - gum
  - hunspell-en_us
  - hunspell-pt-br
  - inotify-tools
  - jdk-openjdk
  - jfsutils
  - ladspa
  - languagetool
  - libappimage
  - libdvdcss
  - libgtop
  - libid3tag
  - libqalculate
  - libsynctex
  - libwmf
  - lolcat
  - lrzip
  - lua-language-server
  - lzop
  - mediainfo
  - mlocate
  - movit
  - neovim-catppuccin-git
  - ninja
  - nmap
  - nodejs
  - npm
  - ntfs-3g
  - opencv
  - openmp
  - opentimelineio
  - p7zip
  - perl
  - perl-bundle-camelcade
  - perl-devel-camelcadedb
  - pstoedit
  - python-lsp-server
  - python-setuptools
  - ruby
  - ruby-docs
  - rust
  - sane-airscan
  - shellcheck
  - snap-pac
  - snapper
  - speech-dispatcher
  - sshfs
  - sshoot
  - sshuttle
  - starship
  - strace
  - subversion
  - tesseract
  - tesseract-data-eng
  - tesseract-data-por
  - tmux
  - trash-cli
  - udftools
  - udiskie
  - unarchiver
  - unzip
  - vcdimager
  - wget
  - xfsprogs
  - yaml-language-server
  - yamlfmt
  - yamllint

desktop_gui:
  - alacritty
  - mpv
  - btrfs-assistant
  - btrfsmaintenance
  - easyeffects
  - gst-plugin-pipewire
  - gst-plugins-bad
  - gst-plugins-good
  - gst-plugins-ugly
  - gtk4
  - kitty
  - meld
  - openrgb
  - power-profiles-daemon
  - qalculate-gtk
  - raw-thumbnailer
  - solaar
  - variety
  - qbittorrent

##
# Gaming packages
# ===============
##
gaming_packages:
  - gamemode
  - gamescope
  - goverlay
  - heroic-games-launcher-bin
  - lib32-dbus
  - lib32-glu
  - lib32-libcurl-compat
  - lib32-mesa
  - lib32-nss
  - lib32-systemd
  - lib32-vkbasalt
  - libva-mesa-driver
  - lutris
  - mangohud
  - mesa
  - protonup-qt
  - sndio
  - steam
  - steamtinkerlaunch
  - v4l2loopback-dkms
  - vkbasalt
  - vkbasalt-cli
  - wf-recorder
