---
- name: Install signal-desktop and discord
  pacman:
    name:
      - signal-desktop
      - discord
      - telegram-desktop
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
