- name: Install QEMU package
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  with_items:
    - qemu-full
    - virt-manager
    - iptables-nft
    - swtpm
    - libtpms
    - dnsmasq

- name: Install VirtIO drivers
  kewlfft.aur.aur:
    state: present
    name: "virtio-win"
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install samba package
  community.general.pacman:
    executable: powerpill
    name: "samba"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Adding existing user '{{ user.name }}' to group libvirt
  user:
    name: '{{ user.name }}'
    groups: libvirt
    append: true

- name: Enable libvirtd services and sockets
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - virtchd.service
    - virtinterfaced.service
    - virtlockd.service
    - virtlogd.service
    - virtlxcd.service
    - virtnetworkd.service
    - virtnodedevd.service
    - virtnwfilterd.service
    - virtproxyd.service
    - virtqemud.service
    - virtsecretd.service
    - virtstoraged.service
    - virtvboxd.service
    - virtchd.socket
    - virtinterfaced.socket
    - virtlockd.socket
    - virtlogd.socket
    - virtlxcd.socket
    - virtnetworkd.socket
    - virtnodedevd.socket
    - virtnwfilterd.socket
    - virtproxyd.socket
    - virtqemud.socket
    - virtsecretd.socket
    - virtstoraged.socket
    - virtvboxd.socket

- name: Start libvirtd services and sockets
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  with_items:
    - virtchd.socket
    - virtinterfaced.socket
    - virtlockd.socket
    - virtlogd.socket
    - virtlxcd.socket
    - virtnetworkd.socket
    - virtnodedevd.socket
    - virtnwfilterd.socket
    - virtproxyd.socket
    - virtqemud.socket
    - virtsecretd.socket
    - virtstoraged.socket
    - virtvboxd.socket

- name: Update nsswitch.conf
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    state: present
    regexp: '^hosts: mymachines resolve .*'
    line: 'hosts: files libvirt libvirt_guest myhostname dns'

- name: Update nsswitch.conf
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    state: present
    regexp: '^hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
    line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files libvirt libvirt_guest myhostname dns'
