- name: install gnome
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  with_items:
    - gnome
    - gnome-extra
    - fwupd
    - gnome-tweaks
    - gnome-shell-extensions
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-arc-menu
    - gnome-shell-extension-vitals
    - gnome-shell-extension-weather-oclock
    - power-profiles-daemon
    - gst-plugin-pipewire
  register: gnome_installed
  until: gnome_installed is success
  retries: 10
  delay: 2
- name: Gnome items from aur
  kewlfft.aur.aur:
    name:
      - gnome-shell-extension-clipboard-indicator
      - gnome-shell-extension-openweather
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-rounded-window-corners
      - gnome-shell-extension-coverflow-alt-tab-git
      - gnome-shell-extension-sound-output-device-chooser
    use: yay
  when: gnome_installed
  become: true
  become_user: "{{ user.name }}"
- name: Enable gdm service
  ansible.builtin.service:
    name: gdm
    enabled: true
  when: gnome_installed
- name: Enable gnome shell extensions
  ansible.builtin.command: gsettings set org.gnome.shell disable-user-extensions false
  register: gnome_extensions_enabled
- name: Enable gnome shell extension - AppIndicator
  ansible.builtin.command: gnome-extensions enable $(gnome-extensions list | grep -m 1 appindicatorsupport)
  when: gnome_extensions_enabled
- name: Enable gnome shell extension - clipboard-indicator
  ansible.builtin.command: gnome-extensions enable $(gnome-extensions list | grep -m 1 clipboard)
  when: gnome_extensions_enabled
- name: Enable gnome shell extension - vitals
  ansible.builtin.command: gnome-extensions enable $(gnome-extensions list | grep -m 1 Vitals)
  when: gnome_extensions_enabled
