- name: Install 1password from aur
  kewlfft.aur.aur:
    state: present
    name: "{{ item }}"
    use: yay
  become: true
  become_user: "{{ user.name }}"
  with_items:
    - 1password
    - 1password-cli
