- name: Install AMDGPU graphics libraries and drivers
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  with_items:
    - lib32-mesa
    - mesa
    - vulkan-radeon
    - lib32-vulkan-radeon
    - libva-mesa-driver
    - lib32-libva-mesa-driver
    - mesa-vdpau
    - lib32-mesa-vdpau
    - amdgpu_top
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
