- name: Install common "desktop" cli tools
  kewlfft.aur.aur:
    name: "{{ desktop_cli }}"
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install common "desktop" GUI tools
  kewlfft.aur.aur:
    name: "{{ desktop_gui }}"
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Set permissions on /game to be owned by users and g=rwx
  file:
    path: "/games"
    state: directory
    group: users
    mode: 0775
  become: true
