- name: Deploy common packages via pacman
  community.general.pacman:
    name:
      - ansible-language-server
      - ansible-lint
      - argyllcms
      - arj
      - atomicparsley
      - atuin
      - bash-completion
      - bash-language-server
      - bat
      - bc
      - darkman
      - catdoc
      - cdrdao
      - cdrtools
      - chezmoi
      - cmake
      - colord-sane
      - cowsay
      - cpanminus
      - ctags
      - diff-so-fancy
      - dosfstools
      - dvd+rw-tools
      - emovix
      - exfatprogs
      - eza
      - f2fs-tools
      - fatresize
      - festival
      - fortune-mod
      - fprintd
      - fzf
      - gavl
      - geoclue
      - geoipupdate
      - git-delta
      - github-cli
      - gnuplot
      - go
      - graphviz
      - gum
      - hunspell-en_us
      - inotify-tools
      - jdk-openjdk
      - jfsutils
      - ladspa
      - languagetool
      - libappimage
      - libappindicator-gtk2
      - libappindicator-gtk3
      - libayatana-appindicator
      - libdvdcss
      - libgtop
      - libid3tag
      - libqalculate
      - libsynctex
      - libwmf
      - lolcat
      - lrzip
      - lua-language-server
      - lzop
      - mediainfo
      - mlocate
      - movit
      - neovim-lspconfig
      - ninja
      - nmap
      - nodejs
      - npm
      - ntfs-3g
      - opencv
      - openmp
      - opentimelineio
      - p7zip
      - perl
      - pstoedit
      - python-lsp-server
      - python-setuptools
      - ripgrep
      - ruby
      - ruby-docs
      - rust
      - sane-airscan
      - shellcheck
      - snap-pac
      - snapper
      - speech-dispatcher
      - sshfs
      - sshuttle
      - starship
      - strace
      - subversion
      - tesseract
      - tesseract-data-eng
      - tesseract-data-por
      - tmux
      - trash-cli
      - udftools
      - udiskie
      - unarchiver
      - unzip
      - vcdimager
      - wget
      - xfsprogs
      - yaml-language-server
      - yamlfmt
      - yamllint
      - jq
      - xmlstarlet
      - rclone
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: Install common "desktop" cli tools via aur
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    aur_only: true
  become: true
  become_user: "{{ user.name }}"
  with_items:
    - ansible-gpg-key-git
    - espanso-wayland-git
    - chezmoi_modify_manager
    - find-the-command
    - hunspell-pt-br
    - neovim-remote
    - perl-bundle-camelcade
    - perl-devel-camelcadedb
    - sshoot

- name: Install common "desktop" GUI tools via pacman
  community.general.pacman:
    name:
      - alacritty
      - cups-browsed
      - easyeffects
      - gst-plugin-pipewire
      - gst-plugins-bad
      - gst-plugins-good
      - gst-plugins-ugly
      - gtk4
      - kitty
      - meld
      - mpv
      - openrgb
      - power-profiles-daemon
      - qalculate-gtk
      - qbittorrent
      - solaar
      - variety
    state: present
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: Install common "desktop" gui tools via aur
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    aur_only: true
  become: true
  become_user: "{{ user.name }}"
  with_items:
    - btop-theme-catppuccin
    - btrfs-assistant
    - btrfsmaintenance
    - flameshot-git
    - raw-thumbnailer
    - webcord-bin

- name: Install tealdeer
  community.general.pacman:
    name:
      - tealdeer
    state: present
  register: installed_tealdeer
  until: installed_tealdeer is success
  retries: 2
  delay: 2

- name: Set permissions on /game to be owned by users and g=rwx
  file:
    path: "/games"
    state: directory
    group: users
    mode: 0775
  become: true

- name: Update tealdeer
  ansible.builtin.command:
    cmd: tealdeer --update
  when: installed_tealdeer
