- name: Install Cosmic
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  with_items:
    - cosmic
  register: cosmic_installed
  until: cosmic_installed is success
  retries: 2
  delay: 2

- name: Enable cosmic-greeter service
  ansible.builtin.service:
    name: cosmic-greeter
    enabled: true
  when: cosmic_installed
