- name: Install Sublime Text
  kewlfft.aur.aur:
    state: present
    name:
      - sublime-text-4
    use: yay
  become: true
  become_user: "{{ user.name }}"
  when: system.type == "desktop"

- name: Install obsidian
  community.general.pacman:
    executable: powerpill
    name: obsidian
    state: present
  when: system.type == "desktop"

- name: Install Libre Office (fresh)
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  with_items:
    - libreoffice-fresh
    - beanshell
    - coin-or-mp
    - gst-plugins-base-libs
    - libmythes
    - libpaper
    - libwpg
    - pstoedit
    - rhino
    - sane
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: Install VSCode
  kewlfft.aur.aur:
    state: present
    name:
      - visual-studio-code-bin
    use: yay
  when: system.type == "desktop"
  become: true
  become_user: "{{ user.name }}"

- name: Install Zed
  kewlfft.aur.aur:
    state: present
    name:
      - zed
    use: yay
  when: system.type == "desktop"
  become: true
  become_user: "{{ user.name }}"

- name: Install neovide
  kewlfft.aur.aur:
    state: present
    name:
      - neovide
    use: yay
  when: system.type == "desktop"
  become: true
  become_user: "{{ user.name }}"

- name: Install neovim package manager LazyVim
  kewlfft.aur.aur:
    state: present
    name:
      - luarocks
      - lua51
    use: yay
  when: system.type == "desktop"
  become: true
  become_user: "{{ user.name }}"

- name: Deploy neovim node package
  ansible.builtin.command: "npm install -g neovim"

- name: Deploy neovim ruby package
  ansible.builtin.command: "gem install neovim"
  become: true
  become_user: "{{ user.name }}"

- name: Deploy perl neovim package
  ansible.builtin.command: "/usr/bin/vendor_perl/cpanm -n Neovim::Ext"
