- name: Install fonts
  kewlfft.aur.aur:
    state: present
    name:
      - apple-fonts
      - fontconfig
      - noto-fonts-emoji
      - otf-font-awesome
      - ttf-dejavu
      - ttf-droid
      - ttf-font-awesome
      - ttf-jetbrains-mono-nerd
      - ttf-liberation
      - ttf-mac-fonts
      - ttf-meslo-nerd-font-powerlevel10k
      - ttf-pragmasevka-nerd-font
      - xorg-font-util
    use: yay
  become: true
  become_user: "{{ user.name }}"
