- name: install fonts
  kewlfft.aur.aur:
    name:
      - apple-fonts
      - fontconfig
      - nerd-fonts-sf-mono
      - noto-fonts-emoji
      - otf-font-awesome
      - ttf-dejavu
      - ttf-droid
      - ttf-font-awesome
      - ttf-liberation
      - ttf-mac-fonts
      - ttf-meslo-nerd-font-powerlevel10k
      - xorg-font-util
    use: yay
  become: true
  become_user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2