- name: Install sddm and associated packages
  kewlfft.aur.aur:
    state: present
    name:
      - gdm
      - gdm-settings
      - gdm-tools
      - arch-gdm-theme-list
      - loginized
      - plymouth-theme-gdm-arch
    use: yay
  become_user: "{{ user.name }}"
  register: gdmed


- name: Enable gdm greeter
  ansible.builtin.service:
    name: gdm
    enabled: true
  when: gdmed
