- name: Install sddm and associated packages
  kewlfft.aur.aur:
    name:
      - gdm
      gdm-settings
    use: yay
  become_user: "{{ user.name }}"
  register: gdmed


- name: Enable gdm greeter
  ansible.builtin.service:
    name: gdm
    enabled: true
  when: gdmed
