- name: Install sddm and associated packages
  kewlfft.aur.aur:
    state: present
    name:
      - gdm
      - gdm-settings
      - gdm-tools
      - arch-gdm-theme-list
      - loginized
      - plymouth-theme-gdm-arch
    use: yay
  become_user: "{{ user.name }}"
