- name: Install gnome
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  with_items:
    - gnome
    - gnome-extra
    - gnome-tweaks
    - gnome-shell-extensions
    - gnome-browser-connector
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-dash-to-panel
    - gnome-shell-extension-weather-oclock
  register: gnome_installed
  until: gnome_installed is success
  retries: 2
  delay: 2

- name: Gnome items from aur
  kewlfft.aur.aur:
    name:
      - gnome-shell-extension-clipboard-indicator
      - gnome-shell-extension-blur-my-shell
      - ulauncher
    use: yay
  when: gnome_installed
  become: true
  become_user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2

- name: Enable gdm service
  ansible.builtin.service:
    name: gdm
    enabled: true
  when: gnome_installed

- name: Enable gnome shell extensions
  ansible.builtin.command: gsettings set org.gnome.shell disable-user-extensions false
