- name: Disable gdm before enabling the specified greeter
  ansible.builtin.systemd_service:
    name: "gdm"
    enabled: false
  when: hyprland_settings.gdm

- name: Disable greetd before enabling the specified greeter
  ansible.builtin.systemd_service:
    name: "greetd"
    enabled: false
  when: hyprland_settings.greetd

- name: Disable sddm before enabling the specified greeter
  ansible.builtin.systemd_service:
    name: "sddm"
    enabled: false
  when: hyprland_settings.sddm

- name: Enable greetd greeter
  ansible.builtin.service:
    name: greetd
    enabled: true
  become: true
  when: hyprland_settings.use_greeter == "greetd"

- name: Enable sddm greeter
  ansible.builtin.service:
    name: sddm
    enabled: true
  when: hyprland_settings.use_greeter == "sddm"

- name: Enable gdm greeter
  ansible.builtin.service:
    name: gdm
    enabled: true
  when: hyprland_settings.use_greeter == "gdm"
