- name: Install Hyprland
  kewlfft.aur.aur:
    name:
      - aquamarine-git
      - hyprcursor-git
      - hypridle-git
      - hyprland-git
      - hyprland-protocols-git
      - hyprlang-git
      - hyprlock-git
      - hyprpaper-git
      - hyprpicker-git
      - hyprutils-git
      - hyprwayland-scanner-git
      - hyprsysteminfo-git
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland-git
    use: yay
  become: true
  become_user: "{{ user.name }}"

# - name: Install Thunar file manager
#   kewlfft.aur.aur:
#     name:
#       - thunar
#       - thunar-volman
#       - thunar-archive-plugin
#       - thunar-media-tags-plugin
#       - tumbler
#       - gvfs
#       - catfish
#       - gvfs-smb
#       - gvfs-onedrive
#       - gvfs-nfs
#       - gvfs-wsdd
#       - engrampa
#       - ark
#       - xarchiver
#       - ffmpegthumbnailer
#       - libgepub
#       - p7zip
#       - unrar
#       - rpm-tools
#       - lha
#       - lzip
#       - unarj
#       - unrar
#     use: yay
#   become: true
#   become_user: "{{ user.name }}"

- name: Install gnome stuff
  community.general.pacman:
    name:
      # - evince
      # - gnome-control-center
      # - gnome-system-monitor
      # - gnome-text-editor
      # - polkit-gnome
      - gvfs-nfs
      - gvfs-onedrive
      - gvfs-smb
      - nautilus
      # - pavucontrol
      # - seahorse-nautilus
    state: present
  become: true
  become_user: "{{ user.name }}"

- name: Install KDE stuff
  community.general.pacman:
    name:
      - qt5-wayland
      - qt6-wayland
      - breeze-icons
      - kvantum
      - kwallet
      - kwallet-pam
      - kwalletmanager
    state: present
  become: true
  become_user: "{{ user.name }}"

- name: Install additional Hyprland tools
  kewlfft.aur.aur:
    name:
      - ags-hyprpanel-git
      - anyrun-git
      - aylurs-gtk-shell
      - bibata-cursor-git
      - blueberry
      - brightnessctl
      - bun-bin
      - cliphist
      - clipse
      - fuzzel
      - grim
      - grimshot
      - jaq
      - lf
      # - mako
      - nm-applet
      - pamixer
      - slurp
      - smile
      - sweet-cursors-hyprcursor-git
      - udiskie
      - udiskie-systemd-git
      - waybar
      - wayprompt
      - webcord-bin
      - wf-recorder
      - wl-clipboard
      - wlogout
      - wofi
      - xwaylandvideobridge-git
      - yad
      - darkman
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install hyprshade
  kewlfft.aur.aur:
    name:
      - hyprshade
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Configure greetd
  ansible.builtin.import_tasks: greetd.yaml
  when: hyprgreetd

- name: Configure SDDM with Hyprland
  ansible.builtin.import_tasks: sddm_hyprland.yaml
  when: hyprsddm
