- name: Install Hyprland
  kewlfft.aur.aur:
    name:
      - aquamarine
      - hyprcursor
      - hypridle
      - hyprland
      - hyprlang
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprsysteminfo
      - hyprutils
      - hyprwayland-scanner
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland
    use: yay
  become: true
  become_user: "{{ user.name }}"

# - name: Install Thunar file manager
#   kewlfft.aur.aur:
#     name:
#       - thunar
#       - catfish
#       - gvfs
#       - tumbler
#       - thunar-volman
#       - thunar-archive-plugin
#       - thunar-media-tags-plugin
#       - zeitgeist
#       - ffmpegthumbnails
#       - libgsf
#       - libgepub
#       - file-roller
#       - engrampa
#       - xarchiver
#     use: yay
#   become: true
#   become_user: "{{ user.name }}"

- name: Install gnome stuff
  kewlfft.aur.aur:
    name:
      - evince
      - gnome-control-center
      - gnome-system-monitor
      - gnome-text-editor
      - gvfs-nfs
      - gvfs-onedrive
      - gvfs-smb
      - nautilus
      - pavucontrol
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install additional Hyprland tools
  kewlfft.aur.aur:
    name:
      - anyrun-git
      - bibata-cursor-git
      - blueberry
      - brightnessctl
      - cliphist
      - dunst
      - fuzzel
      - greetd
      - greetd-regreet-git
      - grim
      - grimshot
      - jaq
      - lf
      - mako
      - nm-applet
      - nordzy-hyprcursors
      - pamixer
      - qt5-wayland
      - qt6-wayland
      - slurp
      - swaybg
      - swayidle
      - swaylock-effects
      - sweet-cursors-hyprcursor-git
      - udiskie
      - udiskie-systemd-git
      - walker-bin
      - waybar
      - webcord-bin
      - wf-recorder
      - wl-clipboard
      - wlogout
      - wofi
      - xwaylandvideobridge-git
      - yad
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install hyprshade
  kewlfft.aur.aur:
    name:
      - hyprshade
    use: yay
  become: true
  become_user: "{{ user.name }}"
  notify: Install hyprshade

- name: Deploy hyprshade config
  ansible.builtin.file:
    path: /usr/share/hyprshade/examples/config.toml
    state: ~/.config/hypr/hyprshade.toml
    mode: '0644'
  notify: Start hyprshade
