- name: Install Hyprland
  kewlfft.aur.aur:
    name:
      - aquamarine-git
      - hyprcursor-git
      - hypridle-git
      - hyprland-git
      - hyprland-protocols-git
      - hyprlang-git
      - hyprlock-git
      - hyprpaper-git
      - hyprpicker-git
      - hyprpolkitagent-git
      - hyprsysteminfo-git
      - hyprutils-git
      - hyprwayland-scanner-git
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland-git
    use: yay
  become: true
  become_user: "{{ user.name }}"

# - name: Install Thunar file manager
#   kewlfft.aur.aur:
#     name:
#       - thunar
#       - thunar-volman
#       - thunar-archive-plugin
#       - thunar-media-tags-plugin
#       - tumbler
#       - gvfs
#       - catfish
#       - gvfs-smb
#       - gvfs-onedrive
#       - gvfs-nfs
#       - gvfs-wsdd
#       - engrampa
#       - ark
#       - xarchiver
#       - ffmpegthumbnailer
#       - libgepub
#       - p7zip
#       - unrar
#       - rpm-tools
#       - lha
#       - lzip
#       - unarj
#       - unrar
#     use: yay
#   become: true
#   become_user: "{{ user.name }}"

- name: Install gnome stuff
  community.general.pacman:
    name:
      # - gnome-control-center
      # - gnome-system-monitor
      # - gnome-text-editor
      # - pavucontrol
      # - polkit-gnome
      - evince
      - gvfs-afc
      - gvfs-dnssd
      - gvfs-goa
      - gvfs-google
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-onedrive
      - gvfs-smb
      - gvfs-wsdd
      - libportal-gtk3
      - libportal-gtk4
      - nautilus
      - seahorse-nautilus
      - network-manager-applet
    state: present
  become: true
  become_user: "{{ user.name }}"

- name: Install KDE stuff
  community.general.pacman:
    name:
      - ark
      - breeze-icons
      - dolphin
      - dolphin-plugins
      - gwenview
      - kvantum
      - kwallet
      - kwallet-pam
      - kwalletmanager
      - okular
      - qt5-wayland
      - qt5ct
      - qt6-wayland
      - qt6ct
      - sddm
    state: present
  become: true
  become_user: "{{ user.name }}"

- name: Install additional Hyprland tools
  kewlfft.aur.aur:
    name:
      # - mako
      - ags-hyprpanel
      - anyrun-git
      - aylurs-gtk-shell
      - bibata-cursor-git
      - blueberry
      - brightnessctl
      - bun-bin
      - cliphist
      - clipse
      - darkman
      - nm-applet
      - fuzzel
      - grim
      - grimshot
      - jaq
      - layer-shell-qt
      - lf
      - pamixer
      - python-pyqt6
      - python-pyqt6-3d
      - python-pyqt6-networkauth
      - python-pyqt6-webengine
      - slurp
      - smile
      - sweet-cursors-hyprcursor-git
      - udiskie
      - udiskie-systemd-git
      - waybar
      - wayprompt
      - wf-recorder
      - wl-clipboard
      - wlogout
      - xwaylandvideobridge-git
      - yad
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install hyprshade
  kewlfft.aur.aur:
    name:
      - hyprshade
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Configure greetd
  ansible.builtin.import_tasks: greetd.yaml
  when: hyprgreetd

- name: Configure SDDM with Hyprland
  ansible.builtin.import_tasks: sddm_hyprland.yaml
  when: hyprsddm
