- name: Install Hyprland
  kewlfft.aur.aur:
    state: present
    name:
      - aquamarine
      - hyprland
      - hyprland-protocols
      - hyprutils-git
      - hyprpolkitagent-git
      - hyprwayland-scanner-git
      - hyprcursor
      - hypridle
      - hyprlang
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprsysteminfo-git
      - hyprsunset
      - xdg-desktop-portal
      - xdg-desktop-portal-hyprland-git
    use: yay
  become: true
  become_user: "{{ user.name }}"
  when: not hyprland_settings.hyprland_git

- name: Install Hyprland
  kewlfft.aur.aur:
    state: present
    name:
      - aquamarine-git
      - hyprland-git
      - hyprland-protocols-git
      - hyprutils-git
      - hyprpolkitagent-git
      - hyprwayland-scanner-git
      - hyprcursor-git
      - hypridle-git
      - hyprlang-git
      - hyprlock-git
      - hyprpaper-git
      - hyprpicker-git
      - hyprsysteminfo-git
      - hyprsunset-git
      - xdg-desktop-portal
      - xdg-desktop-portal-hyprland-git
    use: yay
  become: true
  become_user: "{{ user.name }}"
  when: hyprland_settings.hyprland_git

- name: Install Thunar file manager
  kewlfft.aur.aur:
    state: present
    name:
      - thunar
      - thunar-volman
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - tumbler
      - gvfs
      - catfish
      - gvfs-smb
      - gvfs-onedrive
      - gvfs-nfs
      - gvfs-wsdd
      - engrampa
      - ark
      - xarchiver
      - ffmpegthumbnailer
      - libgepub
      - p7zip
      - unrar
      - rpm-tools
      - lha
      - lzip
      - unarj
      - unrar
    use: yay
  become: true
  become_user: "{{ user.name }}"
  when: hyprland_settings.thunar

- name: Install optional Gnome stuff
  kewlfft.aur.aur:
    state: present
    name:
      - nautilus
      - python-nautilus
      - nautilus-open-any-terminal
      - seahorse-nautilus
      - cheese
      - gnome-photos
      - gnome-connections
      - snapshot
      - cheese
      - nautilus-open-any-terminal
      - yelp
      - gnome-font-viewer
      - gnome-music
      - gnome-characters
      - tali
      - iagno
      - gnome-initial-setup
      - gnome-shell-extensions
      - gnome-maps
      - gnome-boxes
      - gnome-weather
      - gnome-software
#      - network-manager-applet
#      - dconf-editor
#      - gnome-settings-daemon
#      - gnome-online-accounts
    use: yay
  become: true
  become_user: "{{ user.name }}"
  when: hyprland_settings.gnome

- name: Install required Gnome stuff
  kewlfft.aur.aur:
    state: present
    name:
      - morewaita-icon-theme
      - gnome-system-monitor
      - adwaita-icon-theme
      - loupe
      - baobab
      - qogir-icon-theme
      - extension-manager
      - blueberry
      - evince
      - gjs
      - gnome-bluetooth-3.0
      - gnome-control-center
      - gnome-keyring
      - gvfs-afc
      - gvfs-dnssd
      - gvfs-goa
      - gvfs-google
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-onedrive
      - gvfs-smb
      - gvfs-wsdd
      - gnome-themes-extra
      - gobject-introspection
      - polkit-gnome
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install optional KDE stuff
  kewlfft.aur.aur:
    state: present
    name:
      - ark
      - dolphin
      - dolphin-plugins
      - kwallet
      - kwallet-pam
      - kwalletmanager
    use: yay
  become: true
  become_user: "{{ user.name }}"
  when: hyprland_settings.kde

- name: Install required KDE stuff
  kewlfft.aur.aur:
    state: present
    name:
      - breeze-icons
      - ffmpegthumbs
      - gwenview
      - kvantum
      - okular
      - qt5-wayland
      - qt5ct
      - qt6-wayland
      - qt6ct
      - xwaylandvideobridge-git
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install required GTK stuff
  kewlfft.aur.aur:
    state: present
    name:
      - ags-hyprpanel-git
      - aylurs-gtk-shell
      - gtk-engine-murrine
      - gtk-layer-shell
      - gtk3
      - gtksourceview3
      - libportal-gtk3
      - libportal-gtk4
      - xdg-user-dirs-gtk
      - yad
      - ydotool
      - xdg-desktop-portal-gtk
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install MicroTeX (embedded LaTeX rendering library)
  kewlfft.aur.aur:
    state: present
    name:
      - tinyxml2
      - gtkmm3
      - gtksourceviewmm
      - cairomm
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install additional Hyprland tools
  kewlfft.aur.aur:
    state: present
    name:
      - bibata-cursor-git
      - brightnessctl
      - bun-bin
      - cliphist
      - clipse
      - dart-sass
      - ffmpegthumbnailer
      - fuzzel
      - gammastep
      - grim
      - grimblast-git
      - grimshot
      - jaq
      - layer-shell-qt
      - lf
      - libdbusmenu-gtk3
      - mutagen-bin
      - pamixer
      - python-pyqt6
      - python-pyqt6-3d
      - python-pyqt6-networkauth
      - python-pyqt6-webengine
      - sassc
      - slurp
      - smile
      - sweet-cursors-hyprcursor-git
      - swww
      - udiskie
      - udiskie-systemd-git
      - upower
      - waybar
      - wayprompt
      - webp-pixbuf-loader
      - wf-recorder
      - wl-clipboard
      - wlogout
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install hyprshade
  kewlfft.aur.aur:
    state: present
    name:
      - hyprshade
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install Mako notifications
  kewlfft.aur.aur:
    state: present
    name:
      - mako
    use: yay
  become: true
  become_user: "{{ user.name }}"
  when: hyprland_settings.mako


- name: Configure greetd
  ansible.builtin.import_tasks: greetd.yaml
  when: hyprland_settings.greetd

- name: Configure SDDM with Hyprland
  ansible.builtin.import_tasks: sddm_hyprland.yaml
  when: hyprland_settings.sddm

- name: Configure GDM with Hyprland
  ansible.builtin.import_tasks: gdm_hyprland.yaml
  when: hyprland_settings.gdm

- name: Create a symbolic for ags-hyprpanel-git
  ansible.builtin.file:
    src: /usr/share/HyprPanel/
    dest: ~/.config/ags
    state: link
  become: true
  become_user: "{{ user.name }}"
