- name: Install Hyprland
  kewlfft.aur.aur:
    name:
      - aquamarine
      - hyprcursor
      - hypridle
      - hyprland
      - hyprlang
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprutils
      - hyprwayland-scanner
      - hyprsysteminfo
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install Thunar file manager
  kewlfft.aur.aur:
    name:
      - thunar
      - thunar-volman
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - tumbler
      - gvfs
      - catfish
      - gvfs-smb
      - gvfs-onedrive
      - gvfs-nfs
      - gvfs-wsdd
      - engrampa
      - ark
      - xarchiver
      - ffmpegthumbnailer
      - libgepub
      - p7zip
      - unrar
      - rpm-tools
      - lha
      - lzip
      - unarj
      - unrar
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install gnome stuff
  kewlfft.aur.aur:
    name:
      # - evince
      # - gnome-control-center
      # - gnome-system-monitor
      # - gnome-text-editor
      # - polkit-gnome
      # - gvfs-nfs
      # - gvfs-onedrive
      # - gvfs-smb
      # - nautilus
      # - pavucontrol
      # - seahorse-nautilus
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install KDE stuff
  kewlfft.aur.aur:
    name:
      - qt5-wayland
      - qt6-wayland
      - breeze-icons
      - kvantum
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install additional Hyprland tools
  kewlfft.aur.aur:
    name:
      - anyrun-git
      - aylurs-gtk-shell
      - bibata-cursor-git
      - blueberry
      - brightnessctl
      - cliphist
      - fuzzel
      - greetd
      - greetd-regreet-git
      - grim
      - grimshot
      - jaq
      - lf
      - mako
      - nm-applet
      - pamixer
      - slurp
      - sweet-cursors-hyprcursor-git
      - udiskie
      - udiskie-systemd-git
      - waybar
      - webcord-bin
      - wf-recorder
      - wl-clipboard
      - wlogout
      - wofi
      - xwaylandvideobridge-git
      - yad
      - smile
      - clipse
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install hyprshade
  kewlfft.aur.aur:
    name:
      - hyprshade
    use: yay
  become: true
  become_user: "{{ user.name }}"
