- name: Install Hyprland
  kewlfft.aur.aur:
    name:
      - aquamarine
      - hyprcursor
      - hypridle
      - hyprland
      - hyprland-protocols
      - hyprlang
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent-git
      - hyprsysteminfo-git
      - hyprutils-git
      - hyprwayland-scanner
      - xdg-desktop-portal
      - xdg-desktop-portal-hyprland
    use: yay
  become: true
  become_user: "{{ user.name }}"

# - name: Install Thunar file manager
#   kewlfft.aur.aur:
#     name:
#       - thunar
#       - thunar-volman
#       - thunar-archive-plugin
#       - thunar-media-tags-plugin
#       - tumbler
#       - gvfs
#       - catfish
#       - gvfs-smb
#       - gvfs-onedrive
#       - gvfs-nfs
#       - gvfs-wsdd
#       - engrampa
#       - ark
#       - xarchiver
#       - ffmpegthumbnailer
#       - libgepub
#       - p7zip
#       - unrar
#       - rpm-tools
#       - lha
#       - lzip
#       - unarj
#       - unrar
#     use: yay
#   become: true
#   become_user: "{{ user.name }}"
  when: hyprland_settings.gnome

- name: Install gnome stuff
  kewlfft.aur.aur:
    name:
      # - gnome-control-center
      # - gnome-system-monitor
      # - gnome-text-editor
      # - pavucontrol
      # - polkit-gnome
      - evince
      - gvfs-afc
      - gvfs-dnssd
      - gvfs-goa
      - gvfs-google
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-onedrive
      - gvfs-smb
      - gvfs-wsdd
      - libportal-gtk3
      - libportal-gtk4
      - nautilus
      - seahorse-nautilus
      - network-manager-applet
      - dconf-editor
      - gnome settings
      - gnome-online-accounts
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install KDE stuff
  kewlfft.aur.aur:
    name:
      - ark
      - breeze-icons
      - dolphin
      - dolphin-plugins
      - gwenview
      - kvantum
      - kwallet
      - kwallet-pam
      - kwalletmanager
  when: hyprland_settings.kde
      - okular
      - qt5-wayland
      - qt5ct
      - qt6-wayland
      - qt6ct
      - sddm
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install additional Hyprland tools
  kewlfft.aur.aur:
    name:
      - ags-hyprpanel-git
      - anyrun-git
      - aylurs-gtk-shell
      - bibata-cursor-git
      - blueman
      - brightnessctl
      - bun-bin
      - cliphist
      - clipse
      - dart-sass
      - fuzzel
      - gnome-bluetooth-3.0
      - gnome-themes-extra
      - grim
      - grimblast-git
      - grimshot
      - gtk-engine-murrine
      - jaq
      - layer-shell-qt
      - lf
      - mako
      - mutagen-bin
      - nm-applet
      - pamixer
      - python-pyqt6
      - python-pyqt6-3d
      - python-pyqt6-networkauth
      - python-pyqt6-webengine
      - sassc
      - slurp
      - smile
      - sweet-cursors-hyprcursor-git
      - swww
      - udiskie
      - udiskie-systemd-git
      - waybar
      - wayprompt
      - wf-recorder
      - wl-clipboard
      - wlogout
      - xwaylandvideobridge-git
      - yad
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install hyprshade
  kewlfft.aur.aur:
    name:
      - hyprshade
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Configure greetd
  ansible.builtin.import_tasks: greetd.yaml
  when: hyprland_settings.greetd

- name: Configure SDDM with Hyprland
  ansible.builtin.import_tasks: sddm_hyprland.yaml
  when: hyprland_settings.sddm

- name: Create a symbolic for ags-hyprpanel-git
  ansible.builtin.file:
    src: /usr/share/HyprPanel/
    dest: ~/.config/ags
    state: link
  become: true
  become_user: "{{ user.name }}"
