- name: Install  discord, signal-desktop, and telegram
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  with_items:
    - signal-desktop
    - discord
    - telegram-desktop
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
