- name: Install QEMU package
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  with_items:
    - qemu-full
    - virt-manager

- name: Install VirtIO drivers
  kewlfft.aur.aur:
    state: present
    name: "virtio-win"
    use: yay
  become: true
  become_user: "{{ user.name }}"

- name: Install samba package
  community.general.pacman:
    executable: powerpill
    name: "samba"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Adding existing user '{{ user.name }}' to group libvirt
  user:
    name: '{{ user.name }}'
    groups: libvirt
    append: true

- name: Enable libvirtd service
  ansible.builtin.service:
    name: libvirtd.service
    state: started
    enabled: true

- name: Update nsswitch.conf
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    state: present
    regexp: '^hosts: mymachines resolve .*'
    line: 'hosts: files libvirt libvirt_guest myhostname dns'

- name: Update nsswitch.conf
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    state: present
    regexp: '^hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
    line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files libvirt libvirt_guest myhostname dns'
