- name: Deploy rustup
  community.general.pacman:
    name:
      - rustup
    state: present
  register: rusted

- name: Set default rust channel
  ansible.builtin.command:
    cmd: rustup default stable
  when: rusted_channel

- name: Install stable rust
  ansible.builtin.command:
    cmd: rustup update stable
  when: rusted_channel
