- name: Install sddm and associated packages
  community.general.pacman:
    name:
      - sddm
      - qt6-virtualkeyboard
      - weston
      - layer-shell-qt
      - layer-shell-qt5
    state: present
  register: sddmed

- name: Create /etc/sddm.conf.d directory
  ansible.builtin.file:
    path: /etc/sddm.conf.d
    state: directory
    mode: "0755"
  register: created_sddm_conf_d_dir
  when: sddmed

- name: Deploy wayland override config
  ansible.builtin.copy:
    src: sddm-wayland.conf
    dest: /etc/sddm.conf.d/10-wayland.conf
    mode: "0644"
  when: (hyprland_settings.sddm_wayland and created_sddm_conf_d_dir)

- name: Deploy Hyprland compositor config
  ansible.builtin.copy:
    src: sddm-hyprland.conf
    dest: /etc/sddm.conf.d/sddm-hyprland.conf
    mode: "0644"
  when: (hyprland_settings.sddm_wayland and created_sddm_conf_d_dir)

- name: Deploy virtual keyboard config
  ansible.builtin.copy:
    src: sddm-virtualkbd.conf
    dest: /etc/sddm.conf.d/20-virtualkbd.conf
    mode: "0644"
  when: created_sddm_conf_d_dir

- name: Deploy SDDM base theme config
  ansible.builtin.copy:
    src: sddm-base.conf
    dest: /etc/sddm.conf.d/25-base-theme.conf
    mode: "0644"
  when: created_sddm_conf_d_dir

- name: Deploy user avatar config
  ansible.builtin.copy:
    src: sddm-avatar.conf
    dest: /etc/sddm.conf.d/30-avatar.conf
    mode: "0644"
  register: avatared
  when: created_sddm_conf_d_dir
