- name: Install Syncthing
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
  with_items:
    - syncthing

- name: Install Syncthingtray
  kewlfft.aur.aur:
    state: present
    name: "{{ item }}"
    use: yay
  when: kde
  become: true
  become_user: "{{ user.name }}"
  with_items:
    - syncthingtray-qt6

- name: Enable Syncthing user service
  ansible.builtin.systemd_service:
    name: "syncthing"
    state: started
    enabled: true
    scope: "user"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ myuid }}"
