- name: Install Thunderbird
  community.general.pacman:
    executable: powerpill
    name:
      - thunderbird
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
