- name: Install Yubikey Items
  community.general.pacman:
    executable: powerpill
    name: "{{ item }}"
    state: present
  with_items:
    - yubikey-touch-detector
    - yubikey-manager
    - yubikey-pam
    - yubikey-manager-qt
    - yubikey-personalization
    - yubikey-personalization-gui
    - yubico-piv-tool
    - age-plugin-yubikey

- name: Start yubikey-touch-detector
  ansible.builtin.service:
    name: yubikey-touch-detector.service
    scope: user
    state: started
    enabled: true
  become: true
  become_user: "{{ user.name }}"
