---

- name: Install dotfiles management (chezmoi)
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
  become: true
  become_user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  tags:
    - aur
  with_items:
    - chezmoi
    - chezmoi_modify_manager

- name: Clone user dotfiles
  ansible.builtin.git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ user.name }}/{{ dotfiles.destination }}
    accept_hostkey: true
    update: true
    force: true
  when: dotfiles.installation == true
  become: true
  become_user: "{{ user.name }}"

# - name: Install user dotfiles
#   ansible.builtin.command: "rcup -d /home/{{ user.name }}/{{ dotfiles.destination }} {{ dotfiles.rcup_flags }}"
#   when: dotfiles.installation == true
#   become: true
#   become_user: "{{ user.name }}"
