- name: Install ufw
  pacman:
      name: ufw
      state: present

- name: Enable and start ufw
  ansible.builtin.service:
      name: ufw.service
      enabled: true
      state: started

- name: Allow all access from RFC1918 networks to this host
  community.general.ufw:
      rule: allow
      src: "{{ item }}"
  loop:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16

# Allow SSH. (Note that as ufw manages its own state, simply removing
# a rule=allow task can leave those ports exposed. Either use delete=true
# or a separate state=reset task.  See example)
- community.general.ufw:
      rule: allow
      name: SSH

# - name: Delete SSH rule
#   community.general.ufw:
#     rule: allow
#     name: SSH
#     delete: true

- community.general.ufw:
      rule: allow
      name: syncthing

- community.general.ufw:
      rule: allow
      name: Bonjour

- community.general.ufw:
      rule: allow
      name: KTorrent

- community.general.ufw:
      rule: allow
      name: VNC

- community.general.ufw:
      rule: allow
      name: qBittorrent

- community.general.ufw:
      rule: allow
      name: syncthing-gui
