---

- name: Install network tools
  ansible.builtin.package:
    name:
      - ethtool
      - wpa_supplicant
      - dhcpcd
      - nmap
      - networkmanager
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - rkhunter propupdate

- name: Enable NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    state: started
    enabled: true
