---

- name: Install network tools
  ansible.builtin.package:
    name:
      - ethtool
      - wpa_supplicant
      - dhcpcd
      - nmap
      - iwd
      - networkmanager
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - rkhunter propupdate

- name: Enable NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    state: started
    enabled: true

- name: Enable systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved
    state: started
    enabled: true
  register: resolved

- name: deploy disable_mdns
  ansible.builtin.copy: src=1-disable_mdns.conf dest=/etc/systemd/resolved.conf.d/
  notify:
    - restart resolved

- name: deploy stub dns
  ansible.builtin.copy: src=10-stub-dns.conf dest=/etc/systemd/resolved.conf.d/
  when: resolved_stub == True
  notify:
    - restart resolved

- name: switch to systemd-resolved stub dns resolver -- removing resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  register: removed_resolv
  when: resolved

- name: switch to systemd-resolved stub dns resolver -- replacing resolv.conf with symlink
  ansible.builtin.file:
    src: /var/run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
  when: removed_resolv

- name: Update nsswitch.conf
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    state: present
    regexp: '^hosts: mymachines resolve .*'
    line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
