- name: Install syslinux and tools
  community.general.pacman:
    executable: powerpill
    name: syslinux
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: bootloader == "syslinux"
- name: Copy splash image into place
  ansible.builtin.copy:
    src: splash.png
    dest: /boot/syslinux/
- name: Generate and push syslinux configuration
  ansible.builtin.template:
    src: syslinux.cfg.j2
    dest: /boot/syslinux/syslinux.cfg
