- name: install teamspeak3 communication software
  community.general.pacman:
    executable: powerpill
    name: teamspeak3
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
