---

- name: Install secure arch linux environment
  hosts: hosts
  connection: local
  become: true

  roles:
    - { role: network, tags: ["network"] }
    - { role: reflector, tags: ["reflector"] }
    - { role: kernel, tags: ["kernel"] }
    - { role: base, tags: ["base"] }
    - { role: bluetooth, tags: ["bluetooth"], when: "system == 'desktop'" }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: editor, tags: ["editor"] }
    - { role: firewall, tags: ["firewall"] }
    - { role: grub, tags: ["grub"], when: "bootloader == 'grub'" }
    - { role: refind, tags: ["refind"], when: "bootloader == 'refind'" }
    - { role: shell, tags: ["shell"] }
    - { role: terminal, tags: ["terminal"], when: "system == 'desktop'" }
    - { role: windowmanager, tags: ["windowmanager"], when: "system == 'desktop'" }
    - { role: 1password, tags: ["1password"], when: "system == 'desktop'" }
    - { role: amd, tags: ["amd"], when: "system.processor == 'amd'" }
    - { role: browsers, tags: ["browsers"], when: "system == 'desktop'" }
    - { role: calibre, tags: ["calibre"], when: "system == 'desktop'" }
    - { role: games, tags: ["games"], when: "system == 'desktop'" }
    - { role: gitkraken, tags: ["gitkraken"], when: ("gitkraken == 'yes'") and ("system == 'desktop'") }
    - { role: gnupg, tags: ["gnupg"] }
    - { role: jetbrains, tags: ["jetbrains"], when: ("jetbrains == 'yes'") and ("system == 'desktop'") }
    - { role: keepass, tags: ["keepass"], when: "system == 'desktop'" }
    - { role: macspoof, tags: ["macspoof"], when: "system.macspoof == 'enabled'" }
    - { role: mail, tags: ["mail"], when: "system == 'desktop'" }
    - { role: messengers, tags: ["messengers"], when: "system == 'desktop'" }
    - { role: photography, tags: ["photography"], when: "system == 'desktop'" }
    - { role: redshift, tags: ["redshift"], when: ("kde == 'no'") and ("system == 'desktop'") }
    - { role: sound, tags: ["sound"], when: "system == 'desktop'" }
    - { role: spotify, tags: ["spotify"], when: "system == 'desktop'" }
    - { role: syncthing, tags: ["syncthing"] }
