---

- name: Install secure arch linux environment
  hosts: hosts
  connection: local
  become: true

  roles:
    - { role: network, tags: ['network'] }
    - { role: kernel, tags: ['kernel'] }
    - { role: base, tags: ['base'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: grub, tags: ['grub'], when: "bootloader == 'grub'"}
    - { role: syslinux, tags: ['syslinux'], when: "bootloader == 'syslinux'"}
    - { role: refind, tags: ['refind'], when: "bootloader == 'refind'"}
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: shell, tags: ['shell'] }
    - { role: editor, tags: ['editor'] }
    - { role: terminal, tags: ['terminal'] }
    - { role: windowmanager, tags: ['windowmanager'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: bluetooth, tags: ['bluetooth'] }
    - { role: calibre, tags: ['calibre'] }
    - { role: redshift, tags: ['redshift'] }
    - { role: keepass, tags: ['keepass'] }
    - { role: 1password, tags: ['1password'] }
    - { role: spotify, tags: ['spotify'] }
    - { role: macspoof, tags: ['macspoof'], when: "system.macspoof == 'enabled'"}
    - { role: sound, tags: ['sound'] }
    - { role: mail, tags: ['mail'] }
    - { role: photography, tags: ['photography'] }
    - { role: messengers, tags: ['messengers'] }
    - { role: games, tags: ['games'] }
