---

- name: Install secure arch linux environment
  hosts: hosts
  connection: local
  become: true

  roles:
    - { role: network, tags: ["network"] }
    - { role: reflector, tags: ["reflector"] }
    - { role: kernel, tags: ["kernel"] }
    - { role: base, tags: ["base"] }
    - { role: bluetooth, tags: ["bluetooth"], when: system_type == "desktop" }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: editor, tags: ["editor"] }
    - { role: firewall, tags: ["firewall"] }
    - { role: printing, tags: ["printing"] }
    - { role: grub, tags: ["grub"], when: bootloader == "grub" }
    - { role: refind, tags: ["refind"], when: bootloader == "refind" }
    - { role: shell, tags: ["shell"] }
    - { role: terminal, tags: ["terminal"], when: system_type == "desktop" }
    - { role: windowmanager, tags: ["windowmanager"], when: system_type == "desktop" }
    - { role: 1password, tags: ["1password"], when: system_type == "desktop" }
    - { role: amd, tags: ["amd"], when: system.processor == "amd" }
    - { role: browsers, tags: ["browsers"], when: system_type == "desktop" }
    - { role: calibre, tags: ["calibre"], when: system_type == "desktop" }
    - { role: games, tags: ["games"], when: system_type == "desktop" }
    - { role: gitkraken, tags: ["gitkraken"], when: (gitkraken == "yes") and (system_type == "desktop") }
    - { role: gnupg, tags: ["gnupg"] }
    - { role: jetbrains, tags: ["jetbrains"], when: (jetbrains == "yes") and (system_type == "desktop") }
    - { role: keepass, tags: ["keepass"], when: system_type == "desktop" }
    - { role: macspoof, tags: ["macspoof"], when: system.macspoof == "enabled" }
    - { role: mail, tags: ["mail"], when: system_type == "desktop" }
    - { role: messengers, tags: ["messengers"], when: system_type == "desktop" }
    - { role: photography, tags: ["photography"], when: system_type == "desktop" }
    - { role: redshift, tags: ["redshift"], when: (kde == "no") and (system_type == "desktop") }
    - { role: sound, tags: ["sound"], when: system_type == "desktop" }
    - { role: spotify, tags: ["spotify"], when: system_type == "desktop" }
    - { role: syncthing, tags: ["syncthing"] }
