- name: install alacritty terminal emulator
  community.general.pacman:
    executable: powerpill
    name: "alacritty"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
- name: install kitty terminal emulator
  community.general.pacman:
    executable: powerpill
    name: kitty
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
- name: install tmux terminal multiplexer
  community.general.pacman:
    executable: powerpill
    name: tmux
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
