---

- name: Install JetBrains tools (IntelliJ, CLion)
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
  with_items:
      - clion
      - clion-cmake
      - clion-gdb
      - clion-jre
      - clion-lldb
      - intellij-idea-ultimate-edition
      - intellij-idea-ultimate-edition-jre
  become: yes
  become_user: "{{ user.name }}"
