- name: pacman install steam, lutris, and associated tools
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
  with_items: "{{ gaming_packages }}"
  become: true
  become_user: "{{ user.name }}"
