- name: pacman install steam, lutris, and associated tools
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
  with_items: "{{ gaming_packages }}"
  become: true
  become_user: "{{ user.name }}"

- name: arch-specific gaming items
  kewlfft.aur.aur:
    name:
      - steam-hdr
      - steam-native-runtime
    use: yay
  when: system_distribution == "arch"
  become: true
  become_user: "{{ user.name }}"

- name: amd-specific gaming items
  kewlfft.aur.aur:
    name:
      - xf86-video-amdgpu
      - vulkan-radeon
      - lib32-vulkan-radeon
    use: yay
  when: system.graphics_card == "amd"
  become: true
  become_user: "{{ user.name }}"
