---
- name: Install certbot and luadns library
  pacman:
      name: "{{ item }}"
      state: present
  with_items:
      - certbot
      - certbot-dns-luadns
  when: letsencrypt == true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Create /etc/letsencrypt/renewal-hooks/deploy/ directory
  ansible.builtin.file:
      path: /etc/letsencrypt/renewal-hooks/deploy/
      state: directory
      mode: "0755"
  register: created_renewal_hooks_deploy_dir
