- name: Install AMD graphics card specific tooling
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - lib32-libva-mesa-driver
    - lib32-mesa
    - lib32-mesa-vdpau
    - lib32-vulkan-radeon
    - libva-mesa-driver
    - mesa
    - mesa-vdpau
    - vulkan-radeon
    - xf86-video-amdgpu
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  when: system.graphics_card == "amd"
  become: true
  become_user: "{{ user.name }}"
- name: Install AMD graphics card specific tooling from AUR
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
  become: true
  become_user: "{{ user.name }}"
  with_items:
    - opencl-amd
    - rocm-language-runtime
    - rocm-opencl-runtime
    - rocm-smi-lib
    - rocminfo
    - hsa-rocr
- name: Deploy power-dpm systemd service
  ansible.builtin.copy:
    src: power-dpm.service
    dest: /usr/lib/systemd/system/
  register: deployed_power_dpm
- name: power-dpm systemd
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    daemon_reload: true
    name: power-dpm
  when: deployed_power_dpm
