---

- name: Install AMD-specific tooling
  kewlfft.aur.aur:
    name:
      - opencl-amd
  become: true
      - rocm-opencl-runtime
      - rocm-smi-lib
      - rocminfo
    use: yay
    - rocm-opencl-runtime
  become_user: "{{ user.name }}"
